/**
 * State Portal Configuration Seeds
 * Initial data for state WOTC portal configurations
 */

export const statePortalSeeds = [
  {
    stateCode: "CA",
    stateName: "California",
    portalUrl: "https://eddservices.edd.ca.gov/wotc/",
    submissionUrl: "https://eddservices.edd.ca.gov/wotc/upload",
    authType: "credentials",
    loginFieldSelectors: {
      username: "#username",
      password: "#password",
      submitButton: "#loginButton",
      successIndicator: ".dashboard-container"
    },
    requiredColumns: [
      "Employee Last Name",
      "Employee First Name",
      "SSN",
      "Date of Birth",
      "Hire Date",
      "Target Group Code",
      "Disability Status"
    ],
    optionalColumns: [
      "Phone",
      "Email",
      "Veteran Status",
      "SNAP Benefits"
    ],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 250,
    submissionFrequency: "weekly",
    automationEnabled: true,
    expectedProcessingDays: 45,
    supportEmail: "wotc@edd.ca.gov",
    supportPhone: "(916) 464-3300",
    status: "active",
    notes: "California requires additional disability documentation. Use Form EDD 9198."
  },
  {
    stateCode: "NY",
    stateName: "New York",
    portalUrl: "https://labor.ny.gov/wotc/portal",
    submissionUrl: "https://labor.ny.gov/wotc/portal/upload",
    authType: "credentials",
    loginFieldSelectors: {
      username: "input[name='username']",
      password: "input[name='password']",
      submitButton: "button[type='submit']",
      successIndicator: "#wotc-dashboard"
    },
    requiredColumns: [
      "Employee Last Name",
      "Employee First Name",
      "SSN",
      "Date of Birth",
      "Hire Date",
      "Target Group Code",
      "Veteran Documentation"
    ],
    optionalColumns: [
      "Address",
      "City",
      "ZIP",
      "Email"
    ],
    dateFormat: "YYYY-MM-DD",
    maxBatchSize: 200,
    submissionFrequency: "daily",
    automationEnabled: true,
    expectedProcessingDays: 30,
    supportEmail: "wotc.program@labor.ny.gov",
    supportPhone: "(518) 457-9000",
    status: "active",
    notes: "NY requires DD-214 for all veteran claims. Accepts CSV or XML format."
  },
  {
    stateCode: "TX",
    stateName: "Texas",
    portalUrl: "https://www.twc.texas.gov/wotc",
    submissionUrl: "https://www.twc.texas.gov/wotc/submit",
    authType: "credentials",
    loginFieldSelectors: {
      username: "#UserName",
      password: "#Password",
      submitButton: "#LoginBtn",
      successIndicator: ".welcome-message"
    },
    requiredColumns: [
      "Employee Last Name",
      "Employee First Name",
      "SSN",
      "Hire Date",
      "Target Group Code"
    ],
    optionalColumns: [
      "Date of Birth",
      "Address",
      "Phone"
    ],
    dateFormat: "MM-DD-YYYY",
    maxBatchSize: 500,
    submissionFrequency: "daily",
    automationEnabled: true,
    expectedProcessingDays: 21,
    supportEmail: "wotc@twc.texas.gov",
    supportPhone: "(512) 463-2222",
    status: "active",
    notes: "Texas has simplified requirements. Fastest processing time in the country."
  },
  {
    stateCode: "FL",
    stateName: "Florida",
    portalUrl: "https://floridajobs.org/wotc",
    submissionUrl: "https://floridajobs.org/wotc/upload",
    authType: "credentials",
    loginFieldSelectors: {
      username: "#email",
      password: "#pwd",
      submitButton: ".btn-login",
      successIndicator: "#employer-dashboard"
    },
    requiredColumns: [
      "Employee Last Name",
      "Employee First Name",
      "SSN",
      "Date of Birth",
      "Hire Date",
      "Target Group Code",
      "County"
    ],
    optionalColumns: [
      "Email",
      "Phone",
      "Veteran Status"
    ],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 300,
    submissionFrequency: "weekly",
    automationEnabled: true,
    expectedProcessingDays: 35,
    supportEmail: "wotc@deo.myflorida.com",
    supportPhone: "(850) 245-7105",
    status: "active",
    notes: "Florida requires county information for designated community residents."
  },
  {
    stateCode: "IL",
    stateName: "Illinois",
    portalUrl: "https://www.illinoisworknet.com/wotc",
    submissionUrl: "https://www.illinoisworknet.com/wotc/submit",
    authType: "credentials",
    loginFieldSelectors: {
      username: "input#username",
      password: "input#password",
      submitButton: "button.submit-btn",
      successIndicator: ".dashboard-header"
    },
    requiredColumns: [
      "Employee Last Name",
      "Employee First Name",
      "SSN",
      "Date of Birth",
      "Hire Date",
      "Target Group Code"
    ],
    optionalColumns: [
      "Address",
      "Phone",
      "Email",
      "SNAP Status"
    ],
    dateFormat: "YYYY-MM-DD",
    maxBatchSize: 250,
    submissionFrequency: "weekly",
    automationEnabled: false,
    expectedProcessingDays: 40,
    supportEmail: "IDES.WOTC@Illinois.gov",
    supportPhone: "(312) 793-5280",
    status: "active",
    notes: "Illinois portal undergoes maintenance every Sunday 2-6 AM CST."
  },
  {
    stateCode: "PA",
    stateName: "Pennsylvania",
    portalUrl: "https://www.dli.pa.gov/wotc",
    submissionUrl: "https://www.dli.pa.gov/wotc/upload",
    authType: "credentials",
    loginFieldSelectors: {
      username: "input[name='user']",
      password: "input[name='pass']",
      submitButton: "#login-submit",
      successIndicator: "#main-dashboard"
    },
    requiredColumns: [
      "Employee Last Name",
      "Employee First Name",
      "SSN",
      "Date of Birth",
      "Hire Date",
      "Target Group Code"
    ],
    optionalColumns: [
      "Veteran Documentation",
      "TANF Benefits",
      "Email"
    ],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    submissionFrequency: "weekly",
    automationEnabled: false,
    expectedProcessingDays: 42,
    supportEmail: "ra-li-wotc@pa.gov",
    supportPhone: "(717) 787-5279",
    status: "maintenance",
    notes: "Portal currently under renovation. Expected back online Q1 2026."
  },
  {
    stateCode: "OH",
    stateName: "Ohio",
    portalUrl: "https://jfs.ohio.gov/wotc/portal",
    submissionUrl: "https://jfs.ohio.gov/wotc/portal/submit",
    authType: "credentials",
    loginFieldSelectors: {
      username: "#userId",
      password: "#userPassword",
      submitButton: ".login-button",
      successIndicator: ".employer-home"
    },
    requiredColumns: [
      "Employee Last Name",
      "Employee First Name",
      "SSN",
      "Date of Birth",
      "Hire Date",
      "Target Group Code"
    ],
    optionalColumns: [
      "Email",
      "Phone",
      "Address",
      "City",
      "ZIP"
    ],
    dateFormat: "YYYY-MM-DD",
    maxBatchSize: 300,
    submissionFrequency: "daily",
    automationEnabled: true,
    expectedProcessingDays: 28,
    supportEmail: "wotc@jfs.ohio.gov",
    supportPhone: "(614) 466-2319",
    status: "active",
    notes: "Ohio accepts bulk submissions. Fastest turnaround times."
  },
  {
    stateCode: "GA",
    stateName: "Georgia",
    portalUrl: "https://dol.georgia.gov/wotc",
    submissionUrl: "https://dol.georgia.gov/wotc/upload",
    authType: "credentials",
    loginFieldSelectors: {
      username: "#login-email",
      password: "#login-password",
      submitButton: "button.btn-primary",
      successIndicator: ".user-dashboard"
    },
    requiredColumns: [
      "Employee Last Name",
      "Employee First Name",
      "SSN",
      "Date of Birth",
      "Hire Date",
      "Target Group Code"
    ],
    optionalColumns: [
      "SNAP Benefits",
      "Veteran Status",
      "Phone"
    ],
    dateFormat: "MM-DD-YYYY",
    maxBatchSize: 400,
    submissionFrequency: "weekly",
    automationEnabled: true,
    expectedProcessingDays: 33,
    supportEmail: "wotc@gdol.ga.gov",
    supportPhone: "(404) 232-3500",
    status: "active",
    notes: "Georgia prefers weekly batch submissions. No size limit."
  },
  {
    stateCode: "NC",
    stateName: "North Carolina",
    portalUrl: "https://des.nc.gov/wotc",
    submissionUrl: "https://des.nc.gov/wotc/submit",
    authType: "credentials",
    loginFieldSelectors: {
      username: "input#username",
      password: "input#password",
      submitButton: "#btn-login",
      successIndicator: "#dashboard"
    },
    requiredColumns: [
      "Employee Last Name",
      "Employee First Name",
      "SSN",
      "Date of Birth",
      "Hire Date",
      "Target Group Code"
    ],
    optionalColumns: [
      "Address",
      "Phone",
      "Email"
    ],
    dateFormat: "YYYY-MM-DD",
    maxBatchSize: 250,
    submissionFrequency: "weekly",
    automationEnabled: false,
    expectedProcessingDays: 38,
    supportEmail: "wotc@nccommerce.com",
    supportPhone: "(919) 707-1500",
    status: "active",
    notes: "NC requires manual review for veteran claims over $9,000."
  },
  {
    stateCode: "MI",
    stateName: "Michigan",
    portalUrl: "https://www.michigan.gov/leo/wotc",
    submissionUrl: "https://www.michigan.gov/leo/wotc/upload",
    authType: "credentials",
    loginFieldSelectors: {
      username: "input[type='email']",
      password: "input[type='password']",
      submitButton: "button[type='submit']",
      successIndicator: ".welcome-banner"
    },
    requiredColumns: [
      "Employee Last Name",
      "Employee First Name",
      "SSN",
      "Date of Birth",
      "Hire Date",
      "Target Group Code"
    ],
    optionalColumns: [
      "Unemployment Insurance",
      "SNAP Benefits",
      "Veteran Status"
    ],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 300,
    submissionFrequency: "weekly",
    automationEnabled: true,
    expectedProcessingDays: 35,
    supportEmail: "LEO-WOTC@michigan.gov",
    supportPhone: "(517) 335-5858",
    status: "active",
    notes: "Michigan portal is optimized for large batch uploads."
  },
  
  // Remaining states in alphabetical order
  {
    stateCode: "AL",
    stateName: "Alabama",
    portalUrl: "https://labor.alabama.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc@labor.alabama.gov",
    supportPhone: "(334) 242-8003",
    status: "active"
  },
  {
    stateCode: "AK",
    stateName: "Alaska",
    portalUrl: "https://labor.alaska.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 150,
    expectedProcessingDays: 35,
    supportEmail: "wotc@alaska.gov",
    supportPhone: "(907) 465-2700",
    status: "active"
  },
  {
    stateCode: "AZ",
    stateName: "Arizona",
    portalUrl: "https://des.az.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 300,
    expectedProcessingDays: 28,
    supportEmail: "wotc@azdes.gov",
    supportPhone: "(602) 364-2700",
    status: "active"
  },
  {
    stateCode: "AR",
    stateName: "Arkansas",
    portalUrl: "https://www.dws.arkansas.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc@arkansas.gov",
    supportPhone: "(501) 682-2121",
    status: "active"
  },
  {
    stateCode: "CO",
    stateName: "Colorado",
    portalUrl: "https://cdle.colorado.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 250,
    expectedProcessingDays: 25,
    supportEmail: "wotc@state.co.us",
    supportPhone: "(303) 318-8000",
    status: "active"
  },
  {
    stateCode: "CT",
    stateName: "Connecticut",
    portalUrl: "https://www.ct.gov/dol/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc.program@ct.gov",
    supportPhone: "(860) 263-6000",
    status: "active"
  },
  {
    stateCode: "DE",
    stateName: "Delaware",
    portalUrl: "https://dol.delaware.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 150,
    expectedProcessingDays: 28,
    supportEmail: "wotc@delaware.gov",
    supportPhone: "(302) 761-8000",
    status: "active"
  },
  {
    stateCode: "HI",
    stateName: "Hawaii",
    portalUrl: "https://labor.hawaii.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 150,
    expectedProcessingDays: 35,
    supportEmail: "wotc@hawaii.gov",
    supportPhone: "(808) 586-8700",
    status: "active"
  },
  {
    stateCode: "ID",
    stateName: "Idaho",
    portalUrl: "https://www.labor.idaho.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 150,
    expectedProcessingDays: 30,
    supportEmail: "wotc@labor.idaho.gov",
    supportPhone: "(208) 332-3570",
    status: "active"
  },
  {
    stateCode: "IN",
    stateName: "Indiana",
    portalUrl: "https://www.in.gov/dwd/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 250,
    expectedProcessingDays: 28,
    supportEmail: "wotc@dwd.in.gov",
    supportPhone: "(317) 232-7670",
    status: "active"
  },
  {
    stateCode: "IA",
    stateName: "Iowa",
    portalUrl: "https://www.iowaworkforcedevelopment.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc@iwd.iowa.gov",
    supportPhone: "(515) 281-5387",
    status: "active"
  },
  {
    stateCode: "KS",
    stateName: "Kansas",
    portalUrl: "https://www.kansascommerce.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc@kansascommerce.gov",
    supportPhone: "(785) 296-5000",
    status: "active"
  },
  {
    stateCode: "KY",
    stateName: "Kentucky",
    portalUrl: "https://kcc.ky.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc@ky.gov",
    supportPhone: "(502) 564-5331",
    status: "active"
  },
  {
    stateCode: "LA",
    stateName: "Louisiana",
    portalUrl: "https://www.laworks.net/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc@lwc.la.gov",
    supportPhone: "(225) 342-3111",
    status: "active"
  },
  {
    stateCode: "ME",
    stateName: "Maine",
    portalUrl: "https://www.maine.gov/labor/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 150,
    expectedProcessingDays: 32,
    supportEmail: "wotc@maine.gov",
    supportPhone: "(207) 623-7900",
    status: "active"
  },
  {
    stateCode: "MD",
    stateName: "Maryland",
    portalUrl: "https://www.dllr.state.md.us/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 250,
    expectedProcessingDays: 28,
    supportEmail: "wotc@maryland.gov",
    supportPhone: "(410) 767-2000",
    status: "active"
  },
  {
    stateCode: "MA",
    stateName: "Massachusetts",
    portalUrl: "https://www.mass.gov/dcs/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 300,
    expectedProcessingDays: 30,
    supportEmail: "wotc@detma.org",
    supportPhone: "(617) 626-5400",
    status: "active"
  },
  {
    stateCode: "MN",
    stateName: "Minnesota",
    portalUrl: "https://mn.gov/deed/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 250,
    expectedProcessingDays: 28,
    supportEmail: "wotc@state.mn.us",
    supportPhone: "(651) 259-7114",
    status: "active"
  },
  {
    stateCode: "MS",
    stateName: "Mississippi",
    portalUrl: "https://mdes.ms.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc@mdes.ms.gov",
    supportPhone: "(601) 321-6000",
    status: "active"
  },
  {
    stateCode: "MO",
    stateName: "Missouri",
    portalUrl: "https://jobs.mo.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 250,
    expectedProcessingDays: 28,
    supportEmail: "wotc@labor.mo.gov",
    supportPhone: "(573) 751-3215",
    status: "active"
  },
  {
    stateCode: "MT",
    stateName: "Montana",
    portalUrl: "https://dli.mt.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 150,
    expectedProcessingDays: 32,
    supportEmail: "wotc@mt.gov",
    supportPhone: "(406) 444-2840",
    status: "active"
  },
  {
    stateCode: "NE",
    stateName: "Nebraska",
    portalUrl: "https://dol.nebraska.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc@nebraska.gov",
    supportPhone: "(402) 471-9000",
    status: "active"
  },
  {
    stateCode: "NV",
    stateName: "Nevada",
    portalUrl: "https://detr.nv.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 250,
    expectedProcessingDays: 28,
    supportEmail: "wotc@detr.nv.gov",
    supportPhone: "(775) 684-3849",
    status: "active"
  },
  {
    stateCode: "NH",
    stateName: "New Hampshire",
    portalUrl: "https://www.nhes.nh.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 150,
    expectedProcessingDays: 30,
    supportEmail: "wotc@nhes.nh.gov",
    supportPhone: "(603) 224-3311",
    status: "active"
  },
  {
    stateCode: "NJ",
    stateName: "New Jersey",
    portalUrl: "https://www.nj.gov/labor/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 300,
    expectedProcessingDays: 30,
    supportEmail: "wotc@dol.nj.gov",
    supportPhone: "(609) 777-3200",
    status: "active"
  },
  {
    stateCode: "NM",
    stateName: "New Mexico",
    portalUrl: "https://www.dws.state.nm.us/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc@state.nm.us",
    supportPhone: "(505) 841-8405",
    status: "active"
  },
  {
    stateCode: "ND",
    stateName: "North Dakota",
    portalUrl: "https://www.jobsnd.com/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 150,
    expectedProcessingDays: 30,
    supportEmail: "wotc@nd.gov",
    supportPhone: "(701) 328-2825",
    status: "active"
  },
  {
    stateCode: "OK",
    stateName: "Oklahoma",
    portalUrl: "https://oklahoma.gov/oesc/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc@oesc.ok.gov",
    supportPhone: "(405) 557-7100",
    status: "active"
  },
  {
    stateCode: "OR",
    stateName: "Oregon",
    portalUrl: "https://www.oregon.gov/employ/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 250,
    expectedProcessingDays: 28,
    supportEmail: "wotc@oregon.gov",
    supportPhone: "(503) 947-1394",
    status: "active"
  },
  {
    stateCode: "RI",
    stateName: "Rhode Island",
    portalUrl: "https://dlt.ri.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 150,
    expectedProcessingDays: 30,
    supportEmail: "wotc@dlt.ri.gov",
    supportPhone: "(401) 462-8000",
    status: "active"
  },
  {
    stateCode: "SC",
    stateName: "South Carolina",
    portalUrl: "https://dew.sc.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc@dew.sc.gov",
    supportPhone: "(803) 737-2617",
    status: "active"
  },
  {
    stateCode: "SD",
    stateName: "South Dakota",
    portalUrl: "https://dlr.sd.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 150,
    expectedProcessingDays: 30,
    supportEmail: "wotc@state.sd.us",
    supportPhone: "(605) 773-3101",
    status: "active"
  },
  {
    stateCode: "TN",
    stateName: "Tennessee",
    portalUrl: "https://www.tn.gov/workforce/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 250,
    expectedProcessingDays: 28,
    supportEmail: "wotc@tn.gov",
    supportPhone: "(844) 224-5818",
    status: "active"
  },
  {
    stateCode: "UT",
    stateName: "Utah",
    portalUrl: "https://jobs.utah.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 250,
    expectedProcessingDays: 25,
    supportEmail: "wotc@utah.gov",
    supportPhone: "(801) 526-4400",
    status: "active"
  },
  {
    stateCode: "VT",
    stateName: "Vermont",
    portalUrl: "https://labor.vermont.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 150,
    expectedProcessingDays: 30,
    supportEmail: "wotc@vermont.gov",
    supportPhone: "(802) 828-4000",
    status: "active"
  },
  {
    stateCode: "VA",
    stateName: "Virginia",
    portalUrl: "https://www.vec.virginia.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 300,
    expectedProcessingDays: 28,
    supportEmail: "wotc@vec.virginia.gov",
    supportPhone: "(804) 786-3001",
    status: "active"
  },
  {
    stateCode: "WA",
    stateName: "Washington",
    portalUrl: "https://esd.wa.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 300,
    expectedProcessingDays: 25,
    supportEmail: "wotc@esd.wa.gov",
    supportPhone: "(360) 902-9500",
    status: "active"
  },
  {
    stateCode: "WV",
    stateName: "West Virginia",
    portalUrl: "https://workforcewv.org/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 30,
    supportEmail: "wotc@wv.gov",
    supportPhone: "(304) 558-2660",
    status: "active"
  },
  {
    stateCode: "WI",
    stateName: "Wisconsin",
    portalUrl: "https://dwd.wisconsin.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 250,
    expectedProcessingDays: 28,
    supportEmail: "wotc@dwd.wisconsin.gov",
    supportPhone: "(608) 266-3131",
    status: "active"
  },
  {
    stateCode: "WY",
    stateName: "Wyoming",
    portalUrl: "https://wyomingworkforce.org/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 150,
    expectedProcessingDays: 30,
    supportEmail: "wotc@wyo.gov",
    supportPhone: "(307) 235-3254",
    status: "active"
  },
  
  // Washington DC and Territories
  {
    stateCode: "DC",
    stateName: "District of Columbia",
    portalUrl: "https://does.dc.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 28,
    supportEmail: "wotc@dc.gov",
    supportPhone: "(202) 724-7000",
    status: "active"
  },
  {
    stateCode: "PR",
    stateName: "Puerto Rico",
    portalUrl: "https://www.pr.gov/trabajo/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 200,
    expectedProcessingDays: 35,
    supportEmail: "wotc@trabajo.pr.gov",
    supportPhone: "(787) 754-5353",
    status: "active"
  },
  {
    stateCode: "VI",
    stateName: "U.S. Virgin Islands",
    portalUrl: "https://www.vidol.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 100,
    expectedProcessingDays: 40,
    supportEmail: "wotc@vidol.gov",
    supportPhone: "(340) 773-1994",
    status: "active"
  },
  {
    stateCode: "GU",
    stateName: "Guam",
    portalUrl: "https://dol.guam.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 100,
    expectedProcessingDays: 40,
    supportEmail: "wotc@dol.guam.gov",
    supportPhone: "(671) 475-7000",
    status: "active"
  },
  {
    stateCode: "AS",
    stateName: "American Samoa",
    portalUrl: "https://www.americansamoa.gov/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 50,
    expectedProcessingDays: 45,
    supportEmail: "wotc@americansamoa.gov",
    supportPhone: "(684) 699-1371",
    status: "active"
  },
  {
    stateCode: "MP",
    stateName: "Northern Mariana Islands",
    portalUrl: "https://www.cnmidol.gov.mp/wotc",
    authType: "credentials",
    requiredColumns: ["Employee Last Name", "Employee First Name", "SSN", "Hire Date", "Target Group Code"],
    dateFormat: "MM/DD/YYYY",
    maxBatchSize: 50,
    expectedProcessingDays: 45,
    supportEmail: "wotc@cnmidol.gov.mp",
    supportPhone: "(670) 664-3033",
    status: "active"
  }
];

export const getAllStates = () => [
  "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
  "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
  "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
  "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
  "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY",
  "DC", "PR", "VI", "GU", "AS", "MP"
];
